### ISSUE TITLE
Programming ➟ Update manifest with the correct information

### ISSUE THREAD

**Issue by airvzxf** [airvzxf/firefox-extension-efficient-tab-manager#4]
Update the information of the manifest.

- Title is “Efficient Tab Manager”.
- Write a better description.
- Update the homepage to “https://github.com/airvzxf/firefox-extension-efficient-tab-manager”

![EfficientTabManager-manifest](https://user-images.githubusercontent.com/831380/196877861-f3f85d24-c90c-4e99-ba18-c247e05193f4.png)

**Comment by protob** [comment]
Hi, I can take care of this issue

**Comment by airvzxf** [comment]
Thank you!
